models/compra.py
from extensions import db
from datetime import datetime

class Compra(db.Model):
    __tablename__ = 'compras'
    id = db.Column(db.Integer, primary_key=True)
    id_proveedor = db.Column(db.Integer, db.ForeignKey('proveedores.id'))
    fecha_carga = db.Column(db.DateTime, default=datetime.utcnow)  # Cambiado a datetime.utcnow
    iva = db.Column(db.Float, nullable=False)
    total = db.Column(db.Float, nullable=False)


class CompraDetalle(db.Model):
    __tablename__ = 'compras_detalles'
    id = db.Column(db.Integer, primary_key=True)
    compra_id = db.Column(db.Integer, db.ForeignKey('compras.id'), nullable=False)
    producto_id = db.Column(db.Integer, nullable=False)
    producto_nombre = db.Column(db.String(50), nullable=False)  # Almacenar el nombre del producto
    cantidad = db.Column(db.Integer, nullable=False)
    precio_unitario = db.Column(db.Float, nullable=False)

models/producto.py
from extensions import db
from datetime import datetime

class Marca(db.Model):
    __tablename__ = 'marcas'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(50), nullable=False)

    # Relación uno a muchos con Producto
    productos = db.relationship('Producto', backref='marca', lazy=True)

    def to_dict(self):
        return {col.name: getattr(self, col.name) for col in self.__table__.columns}

class Rubro(db.Model):
    __tablename__ = 'rubros'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(50), nullable=False)

    # Relación uno a muchos con Producto
    productos = db.relationship('Producto', backref='rubro', lazy=True)

    def to_dict(self):
        return {col.name: getattr(self, col.name) for col in self.__table__.columns}

class Tipo(db.Model):
    __tablename__ = 'tipos'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(50), nullable=False)

    # Relación uno a muchos con Producto
    productos = db.relationship('Producto', backref='tipo', lazy=True)

    def to_dict(self):
        return {col.name: getattr(self, col.name) for col in self.__table__.columns}


class Producto(db.Model):
    __tablename__ = 'productos'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(50), nullable=False)
    costo = db.Column(db.Float, nullable=False, default=0.0)
    precio = db.Column(db.Float, nullable=False)
    codigo1 = db.Column(db.String(50), nullable=False)
    # Columna para manejar el stock (no nullable)
    stock = db.Column(db.Integer, nullable=False, default=0)
    fecha_creacion = db.Column(db.DateTime, default=datetime.utcnow)


    # Claves foráneas para relacionar Producto con Marca, Rubro y Tipo
    marca_id = db.Column(db.Integer, db.ForeignKey('marcas.id', ondelete='SET NULL'), nullable=True)
    rubro_id = db.Column(db.Integer, db.ForeignKey('rubros.id', ondelete='SET NULL'), nullable=True)
    tipo_id = db.Column(db.Integer, db.ForeignKey('tipos.id', ondelete='SET NULL'), nullable=True)



    # Método para serializar a un diccionario
    def to_dict(self):
        return {col.name: getattr(self, col.name) for col in self.__table__.columns}

views/caja/__init__.py
from .caja import caja_bp

def register_caja_blueprints(app):
    app.register_blueprint(caja_bp)

views/compras/__init__.py
from .compras import compras_bp


def register_compras_blueprints(app):
    app.register_blueprint(compras_bp)

views/productos.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from models.producto import Producto, Rubro, Marca, Tipo  # Asegúrate de que tienes estos modelos definidos
from extensions import db  # Importa tu instancia de base de datos

productos_bp = Blueprint('productos', __name__)

# Rutas para los productos


@productos_bp.route('/productos', methods=['GET'])
def listar_productos():
    productos = Producto.query.all()
    marcas = Marca.query.all()
    rubros = Rubro.query.all()
    tipos = Tipo.query.all()

    if request.accept_mimetypes.best == 'application/json':
        return jsonify({
            'productos': [producto.to_dict() for producto in productos],
            'marcas': [marca.to_dict() for marca in marcas],
            'rubros': [rubro.to_dict() for rubro in rubros],
            'tipos': [tipo.to_dict() for tipo in tipos]
        })

    return render_template('productos.html', productos=productos, marcas=marcas, rubros=rubros, tipos=tipos)


@productos_bp.route('/api/productos', methods=['GET'])
def listar_productos_api():
    productos = Producto.query.all()

    # Retornar la lista de productos en formato JSON
    return jsonify({
        'productos': [producto.to_dict() for producto in productos]
    }), 200  # 200 OK


@productos_bp.route('/agregar_producto', methods=['POST'])
def agregar_producto():
    codigo = request.form.get('codigo')

    # Validar si ya existe el producto con el código proporcionado (opcional)
    producto_existente = Producto.query.filter_by(codigo1=codigo).first()
    if producto_existente:
        flash('El producto ya existe.', 'danger')
        return redirect(url_for('productos.listar_productos'))

    # Si no existe, procede a agregar el producto
    nuevo_producto = Producto(
        nombre=request.form.get('nombre'),
        precio=request.form.get('precio'),
        costo=request.form.get('costo'),
        codigo1=codigo,
        marca_id=request.form.get('marca_id'),
        rubro_id=request.form.get('rubro_id'),
        tipo_id=request.form.get('tipo_id')
    )
    db.session.add(nuevo_producto)
    db.session.commit()

    flash('Producto agregado exitosamente!', 'success')
    return redirect(url_for('productos.listar_productos'))


@productos_bp.route('/api/agregar_producto', methods=['POST'])
def agregar_producto_api():
    if request.is_json:
        data = request.get_json()

        # Validar si ya existe el producto con el código proporcionado
        producto_existente = Producto.query.filter_by(codigo1=data['codigo']).first()
        if producto_existente:
            return {'message': 'El producto ya existe.'}, 400

        # Si no existe, procede a agregar el producto
        nuevo_producto = Producto(
            nombre=data['nombre'],
            precio=data['precio'],
            codigo1=data['codigo'],
            marca_id=data['marca_id'],
            rubro_id=data['rubro_id'],
            tipo_id=data['tipo_id']
        )
        db.session.add(nuevo_producto)
        db.session.commit()

        return {'message': 'Producto agregado exitosamente!'}, 201
    else:
        return {'message': 'La solicitud no es JSON.'}, 400


@productos_bp.route('/productos/editar/<int:id>', methods=['GET', 'POST'])
def editar_producto(id):
    producto = Producto.query.get_or_404(id)
    if request.method == 'POST':
        producto.nombre = request.form['nombre']
        producto.precio = request.form['precio']
        producto.marca_id = request.form['marca_id']
        producto.rubro_id = request.form['rubro_id']
        producto.tipo_id = request.form['tipo_id']
        db.session.commit()
        flash('Producto actualizado exitosamente')
        return redirect(url_for('productos.listar_productos'))
    return render_template('editar_producto.html', producto=producto)


@productos_bp.route('/api/productos/editar/<int:id>', methods=['PUT'])
def editar_producto_api(id):
    producto = Producto.query.get_or_404(id)

    if request.is_json:
        data = request.get_json()
        producto.nombre = data.get('nombre', producto.nombre)  # Si el campo no está presente, no se cambia
        producto.precio = data.get('precio', producto.precio)
        producto.marca_id = data.get('marca_id', producto.marca_id)
        producto.rubro_id = data.get('rubro_id', producto.rubro_id)
        producto.tipo_id = data.get('tipo_id', producto.tipo_id)

        db.session.commit()

        return {'message': 'Producto actualizado exitosamente'}, 200
    else:
        return {'message': 'La solicitud no es JSON'}, 400


@productos_bp.route('/productos/eliminar/<int:id>', methods=['POST'])
def eliminar_producto(id):
    producto = Producto.query.get_or_404(id)
    db.session.delete(producto)
    db.session.commit()
    flash('Producto eliminado exitosamente')
    return redirect(url_for('productos.listar_productos'))


@productos_bp.route('/api/productos/eliminar/<int:id>', methods=['DELETE'])
def eliminar_producto_api(id):
    producto = Producto.query.get_or_404(id)

    db.session.delete(producto)
    db.session.commit()

    return {'message': 'Producto eliminado exitosamente'}, 200

# Rutas para Rubros


@productos_bp.route('/rubros', methods=['GET'])
def listar_rubros():
    rubros = Rubro.query.all()
    return render_template('rubros.html', rubros=rubros)


@productos_bp.route('/rubros/agregar', methods=['POST'])
def agregar_rubro():
    nombre = request.form['nombre']
    nuevo_rubro = Rubro(nombre=nombre)
    db.session.add(nuevo_rubro)
    db.session.commit()
    flash('Rubro agregado exitosamente')

    return redirect(url_for('productos.listar_rubros'))


@productos_bp.route('/rubros/editar/<int:id>', methods=['GET', 'POST'])
def editar_rubro(id):
    rubro = Rubro.query.get_or_404(id)
    if request.method == 'POST':
        rubro.nombre = request.form['nombre']
        db.session.commit()
        flash('Rubro actualizado exitosamente')
        return redirect(url_for('productos.listar_rubros'))
    return render_template('editar_rubro.html', rubro=rubro)


@productos_bp.route('/rubros/eliminar/<int:id>', methods=['POST'])
def eliminar_rubro(id):
    rubro = Rubro.query.get_or_404(id)
    db.session.delete(rubro)
    db.session.commit()
    flash('Rubro eliminado exitosamente')
    return redirect(url_for('productos.listar_rubros'))

# Rutas para Marcas


@productos_bp.route('/marcas', methods=['GET'])
def listar_marcas():
    marcas = Marca.query.all()
    return render_template('marcas.html', marcas=marcas)


@productos_bp.route('/marcas/agregar', methods=['POST'])
def agregar_marca():
    nombre = request.form['nombre']
    nueva_marca = Marca(nombre=nombre)
    db.session.add(nueva_marca)
    db.session.commit()
    flash('Marca agregada exitosamente')

    return redirect(url_for('productos.listar_marcas'))


@productos_bp.route('/marcas/editar/<int:id>', methods=['GET', 'POST'])
def editar_marca(id):
    marca = Marca.query.get_or_404(id)
    if request.method == 'POST':
        marca.nombre = request.form['nombre']
        db.session.commit()
        flash('Marca actualizada exitosamente')
        return redirect(url_for('productos.listar_marcas'))
    return render_template('editar_marca.html', marca=marca)


@productos_bp.route('/marcas/eliminar/<int:id>', methods=['POST'])
def eliminar_marca(id):
    marca = Marca.query.get_or_404(id)
    db.session.delete(marca)
    db.session.commit()
    flash('Marca eliminada exitosamente')
    return redirect(url_for('productos.listar_marcas'))

# Rutas para Tipos


@productos_bp.route('/tipos', methods=['GET'])
def listar_tipos():
    tipos = Tipo.query.all()
    return render_template('tipos.html', tipos=tipos)


@productos_bp.route('/tipos/agregar', methods=['POST'])
def agregar_tipo():
    nombre = request.form['nombre']
    nuevo_tipo = Tipo(nombre=nombre)
    db.session.add(nuevo_tipo)
    db.session.commit()
    flash('Tipo agregado exitosamente')
    return redirect(url_for('productos.listar_tipos'))


@productos_bp.route('/tipos/editar/<int:id>', methods=['GET', 'POST'])
def editar_tipo(id):
    tipo = Tipo.query.get_or_404(id)
    if request.method == 'POST':
        tipo.nombre = request.form['nombre']
        db.session.commit()
        flash('Tipo actualizado exitosamente')
        return redirect(url_for('productos.listar_tipos'))
    return render_template('editar_tipo.html', tipo=tipo)


@productos_bp.route('/tipos/eliminar/<int:id>', methods=['POST'])
def eliminar_tipo(id):
    tipo = Tipo.query.get_or_404(id)
    db.session.delete(tipo)
    db.session.commit()
    flash('Tipo eliminado exitosamente')
    return redirect(url_for('productos.listar_tipos'))

views/productos/__init__.py
from .productos import productos_bp
from .rubros import rubros_bp
from .marcas import marcas_bp
from .tipos import tipos_bp

def register_productos_blueprints(app):
    app.register_blueprint(productos_bp)
    app.register_blueprint(rubros_bp)
    app.register_blueprint(marcas_bp)
    app.register_blueprint(tipos_bp)

views/ventas.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from models.producto import Producto
from models.factura import Factura, FacturaDetalle
from extensions import db
import json

ventas_bp = Blueprint('ventas', __name__)


# Ruta para mostrar los productos
@ventas_bp.route('/ventas')
def ventas():
    productos = Producto.query.all()  # Obtener todos los productos
    return render_template('ventas.html', productos=productos)


# Ruta para procesar la venta
@ventas_bp.route('/procesar_venta', methods=['POST'])
def procesar_venta():
    # Obtener JSON enviado en el cuerpo de la petición
    data = request.get_json()

    productos = data.get('productos', [])
    total_venta = 0

    if productos:
        detalles_factura = []

        # Calcular el total y preparar los detalles de la venta
        for producto_data in productos:
            id_producto = producto_data.get('id')
            cantidad = producto_data.get('cantidad', 1)

            # Imprimir para verificar las cantidades recibidas
            print(f"Producto ID: {id_producto}, Cantidad recibida: {cantidad}")

            # Buscar el producto por ID
            producto = Producto.query.get(id_producto)
            if producto and producto.precio:
                # Calcular el total de la venta
                total_venta += float(producto.precio) * int(cantidad)

                # Crear el detalle de la factura con el nombre del producto
                detalle = FacturaDetalle(
                    producto_id=producto.id,
                    producto_nombre=producto.nombre,
                    cantidad=cantidad,
                    precio_unitario=producto.precio
                )
                detalles_factura.append(detalle)

                # Si la cantidad es negativa, sumar al stock
                if cantidad < 0:
                    print(f"Cantidad negativa detectada para {producto.nombre}: {cantidad}. Sumando al stock.")
                    producto.stock += abs(cantidad)
                else:
                    # Descontar del stock si es positiva
                    producto.stock -= cantidad

                # Guardar los cambios del stock en la base de datos
                db.session.commit()

            else:
                print(f"Producto con ID {id_producto} no encontrado o sin precio")

        print(f"Total de la venta calculado: {total_venta}")

        # Crear la nueva factura y agregar los detalles, independientemente de si el total es positivo o negativo
        nueva_factura = Factura(total=total_venta)
        db.session.add(nueva_factura)
        db.session.commit()  # Necesario para generar el ID de la factura

        # Asignar los detalles de la factura a la factura recién creada
        for detalle in detalles_factura:
            detalle.factura_id = nueva_factura.id
            db.session.add(detalle)

        db.session.commit()  # Guardar los detalles en la base de datos

    return redirect(url_for('ventas.ventas'))

@ventas_bp.route('/buscar_producto')
def buscar_producto():
    codigo = request.args.get('codigo')
    producto = Producto.query.filter_by(codigo1=codigo).first()
    if producto:
        return jsonify({
            'id': producto.id,
            'nombre': producto.nombre,
            'precio': producto.precio
        })
    return jsonify(None), 404

@ventas_bp.route('/buscar_producto_descripcion')
def buscar_producto_descripcion():
    descripcion = request.args.get('descripcion')
    productos = Producto.query.filter(Producto.nombre.ilike(f'%{descripcion}%')).all()
    return jsonify([{
        'id': producto.id,
        'nombre': producto.nombre,
        'precio': producto.precio
    } for producto in productos])
@ventas_bp.route('/buscar_producto_por_id')
def buscar_producto_por_id():
    id_producto = request.args.get('id')
    producto = Producto.query.get(id_producto)
    if producto:
        return jsonify({
            'id': producto.id,
            'nombre': producto.nombre,
            'precio': producto.precio
        })
    return jsonify(None), 404

views/ventas/__init__.py
from .ventas import ventas_bp

def register_ventas_blueprints(app):
    app.register_blueprint(ventas_bp)

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}microPOS{% endblock %}</title>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.13/dist/full.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">


</head>
<body class="bg-gray-100">
    <header>
        {% include 'navbar.html' %}
    </header>
    <main class="max-w-7xl mx-auto p-2">
        {% block content %}
        {% endblock %}
    </main>
    {% block scripts %}
    {% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Bienvenido - kPOS{% endblock %}

{% block content %}
<h2 class="text-2xl mb-4 font-semibold">Bienvenido!</h2>
<!-- Agrega aquí el contenido específico de la página -->

{% endblock %}

templates/productos.html
{% extends 'base.html' %}

{% block title %}Productos - kPOS{% endblock %}

{% block content %}
<h2 class="text-2xl mb-4 font-semibold">Productos</h2>


<!-- Contenedor principal con diseño de cuadrícula -->
<div class="grid grid-cols-4 gap-6 p-1">
    <!-- Contenedor de formulario para agregar productos (1/4) -->
    <div class="col-span-1 bg-white shadow-md rounded-lg p-4">
        <h2 class="text-2xl font-semibold mb-4">Agregar Producto</h2>
        <form action="{{ url_for('productos.agregar_producto') }}" method="POST" class="mb-6">
            <label class="input input-bordered flex items-center gap-2 mb-2">
                <input type="text" name="nombre" placeholder="Nombre del producto" required class="grow" autocomplete="off">
                <i class="bi bi-box-fill h-4 w-4 opacity-70"></i>
            </label>

            <label class="input input-bordered flex items-center gap-2 mb-2">
                <input type="number" name="costo" placeholder="Precio de costo" required class="grow" />
                <i class="bi bi-receipt h-4 w-4 opacity-70"></i>
            </label>

            <label class="input input-bordered flex items-center gap-2 mb-2">
                <input type="number" name="precio" placeholder="Precio de venta" required class="grow" />
                <i class="bi bi-cash h-4 w-4 opacity-70"></i>
            </label>

            <label class="input input-bordered flex items-center gap-2 mb-2">
                <input type="text" id="codigoInput" name="codigo" placeholder="Código de barras" required class="grow" autocomplete="off">
                <i class="bi bi-upc h-4 w-4 opacity-70"></i>
            </label>

            <!-- Selección de Marca -->
            <div class="flex items-center gap-2 mb-2">
                <div class="flex-grow">
                    <label for="marca_id" class="block mb-1">Marca</label>
                    <select name="marca_id" id="marca_id" required class="select select-bordered w-full">
                        {% for marca in marcas %}
                            <option value="{{ marca.id }}">{{ marca.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <a href="{{ url_for('marcas.listar_marcas') }}" class="btn btn-square btn-sm">
                    <i class="bi bi-gear-fill"></i>
                </a>
            </div>

            <!-- Selección de Rubro -->
            <div class="flex items-center gap-2 mb-2">
                <div class="flex-grow">
                    <label for="rubro_id" class="block mb-1">Rubro</label>
                    <select name="rubro_id" id="rubro_id" required class="select select-bordered w-full">
                        {% for rubro in rubros %}
                            <option value="{{ rubro.id }}">{{ rubro.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <a href="{{ url_for('rubros.listar_rubros') }}" class="btn btn-square btn-sm">
                    <i class="bi bi-gear-fill"></i>
                </a>
            </div>

            <!-- Selección de Tipo -->
            <div class="flex items-center gap-2 mb-2">
                <div class="flex-grow">
                    <label for="tipo_id" class="block mb-1">Tipo</label>
                    <select name="tipo_id" id="tipo_id" required class="select select-bordered w-full">
                        {% for tipo in tipos %}
                            <option value="{{ tipo.id }}">{{ tipo.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <a href="{{ url_for('tipos.listar_tipos') }}" class="btn btn-square btn-sm">
                    <i class="bi bi-gear-fill"></i>
                </a>
            </div>

            <button type="submit" class="btn btn-primary w-full">Agregar Producto</button>
        </form>
    </div>

    <!-- Contenedor de productos con desplazamiento interno (3/4) -->
    <div class="col-span-3 bg-white shadow-md rounded-lg p-4">
        <input type="text" placeholder="Escribe para buscar" class="input w-full max-w-xs mb-4"/>
        <div class="overflow-x-auto h-[400px]">
            <table class="table table-xs table-pin-rows table-pin-cols">
                <thead>
                    <tr>
                        <th></th>
                        <td style="width: 100px;">Código</td>
                        <td style="max-width: 300px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">Nombre</td>
                        <td>Costo</td>
                        <td>Precio</td>
                        <td>Stock</td>
                        <td>Acciones</td>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr class="{% if loop.index is even %}bg-gray-100{% else %}bg-white{% endif %}">
                        <th>{{ loop.index }}</th>
                        <td>{{ producto.codigo1 }}</td>
                        <td style="max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ producto.nombre }}</td>
                        <td>${{ producto.costo }}</td>
                        <td>${{ producto.precio }}</td>
                        <td>{{ producto.stock }}</td>
                        <td>
                            <a href="{{ url_for('productos.editar_producto', id=producto.id) }}" class="text-blue-500 hover:underline">Editar</a>
                            <form action="{{ url_for('productos.eliminar_producto', id=producto.id) }}" method='POST' style='display:inline;'>
                                <button type='submit' class='text-red-500 hover:underline ml-4'>Eliminar</button>
                            </form>
                        </td>
                        <th>{{ loop.index }}</th>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <td>Código</td>
                        <td>Nombre</td>
                        <td>Costo</td>
                        <td>Precio</td>
                        <td>Stock</td>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>

        <!-- Formulario para cargar productos (XLS/XLSX) -->
        <div class="mt-4">
            <h3 class="text-xl font-semibold mb-2">Cargar archivo de productos (XLS/XLSX)</h3>
            <form action="{{ url_for('productos.cargar_productos') }}" method="POST" enctype="multipart/form-data" class="flex items-center gap-4">
                <input type="file" id="file" name="file" required class="border border-gray-300 rounded p-2 w-full">
                <button type='submit' class='bg-blue-600 text-white px-4 py-2 rounded hover:bg-green-500 transition duration-300'>Cargar Productos</button>
            </form>
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='productos/productos.js') }}"></script>
{% endblock %}

templates/ventas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ventas - kPOS</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='ventas/styles-venta.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
</head>
<body class="bg-gray-100">

    <!-- Incluyendo la navbar -->
    {% include 'navbar.html' %}

    <br>

    <!-- Contenedor principal con flexbox para organizar columnas -->
    <div class="flex justify-between space-x-4 px-6" style="height: 600px;">
        <!-- Columna izquierda con altura fija -->
        <div class="left-column w-4/5 bg-white shadow-md rounded-lg p-4 h-full overflow-y-auto">
            <br>
            <!-- Tabla para productos -->
            <div class="overflow-x-auto">
                <table class="min-w-full bg-white">
                    <thead>
                        <tr class="w-full bg-white">
                            <th class="text-left py-2 px-0">Código</th>
                            <th class="text-left py-2 px-0">Descripción</th>
                            <th class="text-left py-2 px-0">Cantidad</th>
                            <th class="text-right py-2 px-1">Precio</th>
                            <th class="text-right py-2 px-4">Subtotal</th>
                            <th class="text-center py-2 px-1">Acc.</th>
                        </tr>
                    </thead>
                    <tbody id="lista-productos">
                        <!-- Aquí se llenarán los productos agregados -->
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Columna derecha con dos contenedores -->
        <div class="flex flex-col w-2/5 space-y-4">
            <!-- Contenedor derecho superior con altura fija -->
            <div class="right-column w-full bg-white shadow-md rounded-lg p-4" style="height: 900px;">
                <form id="form-venta" onsubmit="event.preventDefault(); agregarProductoPorCodigo(document.getElementById('codigo').value);">
<input type="text" id="codigo" placeholder="Código de producto" required class="border border-gray-300 rounded p-2 mb-4 w-full" autocomplete="off">
                </form>
                <div class="mt-4 flex space-x-4">
                    <button onclick="procesarVenta()" class="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-500 transition duration-300">Realizar Venta</button>
                    <button onclick="mostrarModal()" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-500 transition duration-300">Buscar producto por descripción</button>
                </div>
            </div>

            <!-- Tercer contenedor (total), también con altura fija -->
            <div class="right-column bg-green-500 shadow-md rounded-lg p-4" style="height: 230px;">
                <h3 id="total" class="text-5xl font-bold align-center">Total: $0.00</h3>
            </div>
        </div>
    </div>

    <div id="modal-buscar" class="modal">
        <div class="modal-content">
            <span class="close" onclick="cerrarModal()">&times;</span>
            <h2>Buscar Producto por Descripción</h2>
            <input type="text" id="descripcion" placeholder="Escribe para buscar..." oninput="buscarProductoPorDescripcion()" onkeydown="manejarTeclasNavegacion(event)" autocomplete="off" class="border border-gray-300 rounded p-2 mb-4 w-full">
            <ul id="resultado-busqueda">
                <!-- Aquí se mostrarán los resultados de búsqueda -->
            </ul>
        </div>
    </div>

<script>
    const urlProcesarVenta = "{{ url_for('ventas.procesar_venta') }}";
</script>
    <script src="{{ url_for('static', filename='ventas/app-focus.js') }}"></script>
    <script src="{{ url_for('static', filename='ventas/productos.js') }}"></script>
    <script src="{{ url_for('static', filename='ventas/modal.js') }}"></script>
    <script src="{{ url_for('static', filename='ventas/venta.js') }}"></script>
    <script src="{{ url_for('static', filename='ventas/navegarfactura.js') }}"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

</body>
</html>